# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: By Design or By Disaster 2016
email: designdisaster@unibz.it
description: > # this means to ignore newlines until "baseurl:"
  Conference on Design and Communication for Eco-Social Transitions, 2 - 7 May 2016, Free University of Bolzano-Bozen | Italia
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://designdisaster2016.unibz.it/" # the base hostname & protocol for your site
facebook: https://www.facebook.com/designdisaster
twitter: https://twitter.com/designdisasterr

# Build settings
markdown: kramdown

# File exclusion
exclude: [
  "README.md"
]
